FROM node:alpine

WORKDIR '/app'

#copy just package.json file to WORKDIR
COPY package.json .
RUN npm install

#copy everything from host CWD to docker container WORKDIR
COPY . .

CMD ["npm", "run", "start"]
